version: "3.9"

services:
  db:
    image: postgres:15
    container_name: servicehub-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servicehub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

