"""update

Revision ID: 8b604f4a5e28
Revises: b07075d07953
Create Date: 2025-05-07 14:48:47.662774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b604f4a5e28'
down_revision: Union[str, None] = 'b07075d07953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('services', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###
